version: '3.8'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: keycloak
    command: start --optimized
    environment:
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Q9@7nhUr9g
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: 'false'
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/certs/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/certs/tls.key
      KC_HTTPS_PORT: 8443
      KC_HOSTNAME_STRICT: 'false'
    ports:
      - "7443:8443"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - /srv/keycloak/certs:/opt/keycloak/certs:ro
    depends_on:
      - db
    restart: unless-stopped
